# Generated by Django 5.1.3 on 2024-11-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("check_server", "0002_alter_alert_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="ip",
            new_name="ipv4",
        ),
        migrations.AlterUniqueTogether(
            name="server",
            unique_together={("ipv4", "username")},
        ),
    ]
