# Generated by Django 5.1.3 on 2024-11-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("check_server", "0008_company_date_joined_company_updated"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="application",
            unique_together=set(),
        ),
    ]
