# Generated by Django 5.1.3 on 2024-11-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("check_server", "0009_alter_application_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["port"]},
        ),
    ]
