# Generated by Django 5.1.3 on 2024-12-02 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_server", "0010_alter_application_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DockerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_run_on_docker", models.CharField(max_length=50)),
                ("container_name", models.CharField(max_length=50)),
                ("port", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="check_server.company",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="check_server.server",
                    ),
                ),
            ],
        ),
    ]
