# Generated by Django 5.1.3 on 2024-12-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_server", "0011_dockerapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="docker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="check_server.dockerapplication",
            ),
        ),
    ]
